import os
import re
from typing import Iterable

from datatrove.data import Document
from datatrove.utils._import_utils import ASSETS_PATH

from ..writers.disk_base import DiskWriter
from .base_filter import BaseFilter


BLOCKLIST_FILE = os.path.join(ASSETS_PATH, "commoncrawl_optout.txt")

scheme_re = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*://")


def url_path(url: str) -> str:
    """Extract the path of a url, without the query string, fragment or surrounding slashes."""
    return scheme_re.sub("", url.strip()).partition("/")[2].split("?")[0].split("#")[0].lower().strip("/")


def parse_blocklist(lines: Iterable[str]) -> dict[str, list[str]]:
    """
    Build a `{host: [path_prefixes]}` mapping. An empty prefix list means the whole host is blocked.

    Entries are expected to be already normalized, as `tools/build_commoncrawl_optout.py` writes them.
    """
    blocklist = {}
    for line in lines:
        entry = line.split("#")[0].strip().lower()
        if not entry:
            continue
        host, _, path = entry.partition("/")
        if blocklist.get(host) == []:
            continue  # whole host already blocked, any path rule under it is redundant
        if not path:
            blocklist[host] = []
        else:
            blocklist.setdefault(host, []).append(path)
    return blocklist


class CommonCrawlOptOutFilter(BaseFilter):
    """
    Removes documents whose url was reported to the Common Crawl opt-out list, i.e. sites whose owners asked
    to be excluded from the crawl.

    Blocklist entries are either a bare host (`example.com`, which also covers every subdomain of it) or a
    host with a path prefix (`example.com/user/someone`, which covers that page and anything below it).
    Matching ignores the scheme, a leading `www.`, and case, since none of those reliably identify a site.

    The bundled list is generated by `tools/build_commoncrawl_optout.py`, which is where the messy source
    spreadsheet gets cleaned up. Entries are therefore assumed to be normalized already.

    Args:
        blocklist_file: path to the blocklist. Defaults to the list bundled in datatrove's assets.
        extra_entries: additional entries, normalized like the file: lowercase `host` or `host/path`,
            with no scheme and no leading `www.`
        use_integrated_list: set to False to only use `extra_entries`
        exclusion_writer: optionally save the dropped documents
    """

    name = "🚫 CommonCrawl opt-out"
    _requires_dependencies = ["tldextract"]

    def __init__(
        self,
        blocklist_file: str = BLOCKLIST_FILE,
        extra_entries: Iterable[str] = None,
        use_integrated_list: bool = True,
        exclusion_writer: DiskWriter = None,
    ):
        from tldextract import TLDExtract

        super().__init__(exclusion_writer)
        entries = []
        if use_integrated_list:
            with open(blocklist_file, encoding="utf-8") as f:
                entries.extend(f)
        if extra_entries:
            entries.extend(extra_entries)
        self.blocklist = parse_blocklist(entries)
        self.tldextractor = TLDExtract()

    def filter(self, doc: Document) -> bool | tuple[bool, str]:
        url = doc.metadata.get("url")
        assert url, "Document does not have url in its metadata"

        url_info = self.tldextractor(url)
        fqdn = url_info.fqdn.lower()
        if fqdn.startswith("www."):
            fqdn = fqdn[4:]
        path = url_path(url)

        # a subdomain match is more specific, so it takes precedence over the registered domain
        for host in (fqdn, url_info.registered_domain.lower()):
            prefixes = self.blocklist.get(host)
            if prefixes is None:
                continue
            if not prefixes:
                return False, "domain"
            for prefix in prefixes:
                # only match on a path separator, so /users/bob does not match /users/bobby
                if path.startswith(prefix) and (len(path) == len(prefix) or path[len(prefix)] == "/"):
                    return False, "url"

        return True
